### ISSUE TITLE
Does W['5'] in vgg need adjustment for previous layer dropout?

### ISSUE THREAD

**Issue by mikowals** [hendrycks/init#1]
Just reading the code and since dropout is applied before and after its convolutional layer, I would have thought `W['5']` would follow the same initialization pattern as the other layers.   Refering to [this line](https://github.com/hendrycks/init/blob/master/cifar10_vgg.py#L91) using `c_forward/0.6` instead of `c_forward` only.

Sorry to bother you if I am misunderstanding something.

**Comment by hendrycks** [comment]
Good catch. I'll re-run the experiments with the fix later this year.
